name: CI

on:
  push:
    branches:
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install hadolint
        run: sudo apt-get install -y hadolint
      - name: Lint Dockerfile
        run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/karsajobs-ui:latest .
          docker push ghcr.io/${{ github.repository_owner }}/karsajobs-ui:latest
